### ISSUE TITLE
Cannot publish android

### ISSUE THREAD

**Issue by Spelt** [gmurt/MonkeyBuilder#2]
Hi Graham,

There looks to be a problem with the 'Get aliases' for Android.  I does nothing at all.

Looks promising but cant get it to work yet.

Regards
Edward

**Comment by gmurt** [comment]
Hi Edward, 
I hope you're well.  Apologies for the delay in replying... I just haven't had time to look at this project for some time.  
Now open sourced so please see if the latest version works better for you.

**Comment by Spelt** [comment]
I was pressed for time too. Crazy year here. 
I’ll take a look soon. 

Thanks!
